
fiske-region:
  normal: "fiske"
  by: "fiske-by"

NPC:
  FishPrizeMenu: "50"
  FishPrizeMenuByen: "51"

Fish:
  chances:
    normal:
      legendary: 0.08
      epic: 0.4
      rare: 4.4
      uncommon: 21.42
      common: 73.7
    by:
      legendary: 0.1
      epic: 0.5
      rare: 5.6
      uncommon: 25.6
      common: 63.2

mainMenu:
  common: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDBmZDY3OTc4MDE0OTY5YzVmNTE3MmJmMzlkMjQzNDcyODFkNmQ5NWFlNzBmMTliNDlkODRmMWY4ZmVlNjg1In19fQ=="
  uncommon: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODUyODQ5YjY0NWZjZTg2YWNiZDIzMTk5MWJhOTBkMjBkYTQyZTNhOWE4YjU4ZTc2ZGQ0ZTM4NmRiZThiIn19fQ=="
  rare: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2RiMTc5YWUyYmZkOGRlNjdiZmIyYmMzMDhhMjEzNGJkNzUxOTQyZDM0Mjg3NGY4NmI1NzQ3ZDE2ZWVkNzIifX19"
  epic: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDZiMDdlNzEyNThkYjhmZTI0MWJjNjU5ZTg3NDk0MWNjYjNkMTJjNzVlNDgyZWE5YjUwYTA0OGU2Njc3YTMifX19"
  legendary: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDc4YzFiZDliMzQwZmIzODdjMTNiOGI2ZDdhNzUxYzM4NDY2OTI2MmIyNWM2NGJkMjg1YzQ2MzBlZWY0ZmEifX19"

